name = "relationship-vectorize-worker"
main = "src/workers/vectorize_relationship_data.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "megan-personal"
database_id = "f450193b-9536-4ada-8271-2a8cd917069e"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "relationship-insights"

[ai]
binding = "AI"

[vars]
ANTHROPIC_API_KEY = "your-api-key-here"

[env.production]
vars = { ENVIRONMENT = "production" }