name = "csv-import-worker"
main = "src/workers/csv-import-worker.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "megan-personal"
database_id = "f450193b-9536-4ada-8271-2a8cd917069e"

[env.production]
vars = { ENVIRONMENT = "production" }